Select ACTNO, CNAME, AMOUNT FROM DEPOSIT

Select LOANNO,AMOUNT FROM BORROW

Select *FROM BORROW WHERE BNAME='ANDHERI'

Select ACTNO, AMOUNT FROM DEPOSIT WHERE ACTNO=106

Select *FROM BORROW WHERE AMOUNT>5000

Select *FROM DEPOSIT WHERE ADATE='1996-12-1'

Select *FROM DEPOSIT WHERE ACTNO<105

SELECT *FROM CUSTOMERS WHERE CITY='NAGPUR' OR CITY='DELHI'

Select *FROM DEPOSIT WHERE AMOUNT>4000 AND ACTNO<105
 
Select *FROM BORROW WHERE AMOUNT>=3000 AND AMOUNT<=8000

Select *FROM DEPOSIT WHERE BNAME!='ANDHERI'

Select ACTNO, CNAME, AMOUNT FROM DEPOSIT WHERE BNAME='AJNI' OR BNAME='KAROLBAGH' OR BNAME='M.G. ROAD' AND ACTNO<104
