SELECT TOP 5 *FROM DEPOSIT

SELECT TOP 3 *FROM DEPOSIT WHERE AMOUNT>1000

SELECT TOP 5 LOANNO, CNAME FROM BORROW WHERE BNAME!='ANDHERI'

SELECT DISTINCT CITY FROM CUSTOMERS 

SELECT DISTINCT BNAME FROM BRANCH 